import postgres from "postgres"

async function migrate() {
  const client = postgres("postgresql://jay:jay_dev_password@localhost:5432/jay_office")
  
  // All tables via raw SQL (CREATE TABLE IF NOT EXISTS)
  const sql = `
    CREATE TABLE IF NOT EXISTS "users" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "email" varchar(320) NOT NULL, "password_hash" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "avatar_url" text, "email_verified" boolean DEFAULT false NOT NULL, "email_verification_token" varchar(255), "email_verification_expires" timestamp, "two_factor_enabled" boolean DEFAULT false NOT NULL, "two_factor_secret" varchar(255), "recovery_codes" jsonb, "created_at" timestamp DEFAULT now() NOT NULL, "updated_at" timestamp DEFAULT now() NOT NULL);
    CREATE TABLE IF NOT EXISTS "workspaces" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "name" varchar(255) NOT NULL, "slug" varchar(64) NOT NULL, "plan" varchar(32) DEFAULT 'free' NOT NULL, "storage_used" bigint DEFAULT 0 NOT NULL, "storage_limit" bigint DEFAULT 5368709120 NOT NULL, "created_at" timestamp DEFAULT now() NOT NULL, "updated_at" timestamp DEFAULT now() NOT NULL);
    CREATE TABLE IF NOT EXISTS "workspace_members" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "workspace_id" uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, "user_id" uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, "role" varchar(32) DEFAULT 'viewer' NOT NULL, "created_at" timestamp DEFAULT now() NOT NULL);
    CREATE TABLE IF NOT EXISTS "sessions" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "user_id" uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, "refresh_token" varchar(512) NOT NULL, "device_info" varchar(512), "ip_address" varchar(45), "expires_at" timestamp NOT NULL, "created_at" timestamp DEFAULT now() NOT NULL);
    CREATE TABLE IF NOT EXISTS "folders" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "name" varchar(512) NOT NULL, "workspace_id" uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, "owner_id" uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, "parent_id" uuid REFERENCES folders(id) ON DELETE CASCADE, "created_at" timestamp DEFAULT now() NOT NULL, "updated_at" timestamp DEFAULT now() NOT NULL);
    CREATE TABLE IF NOT EXISTS "files" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "name" varchar(512) NOT NULL, "mime_type" varchar(255) NOT NULL, "size" bigint NOT NULL, "key" varchar(1024) NOT NULL, "workspace_id" uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, "owner_id" uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, "folder_id" uuid REFERENCES folders(id) ON DELETE SET NULL, "starred" boolean DEFAULT false NOT NULL, "trashed" boolean DEFAULT false NOT NULL, "trashed_at" timestamp, "created_at" timestamp DEFAULT now() NOT NULL, "updated_at" timestamp DEFAULT now() NOT NULL);
    CREATE TABLE IF NOT EXISTS "documents" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "title" varchar(512) DEFAULT 'Untitled Document' NOT NULL, "workspace_id" uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, "owner_id" uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, "file_id" uuid REFERENCES files(id) ON DELETE SET NULL, "content" text, "version" integer DEFAULT 1 NOT NULL, "created_at" timestamp DEFAULT now() NOT NULL, "updated_at" timestamp DEFAULT now() NOT NULL);
    CREATE TABLE IF NOT EXISTS "sheets" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "title" varchar(512) DEFAULT 'Untitled Sheet' NOT NULL, "workspace_id" uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, "owner_id" uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, "file_id" uuid REFERENCES files(id) ON DELETE SET NULL, "content" text, "version" integer DEFAULT 1 NOT NULL, "created_at" timestamp DEFAULT now() NOT NULL, "updated_at" timestamp DEFAULT now() NOT NULL);
    CREATE TABLE IF NOT EXISTS "slides" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "title" varchar(512) DEFAULT 'Untitled Presentation' NOT NULL, "workspace_id" uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, "owner_id" uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, "file_id" uuid REFERENCES files(id) ON DELETE SET NULL, "content" text, "version" integer DEFAULT 1 NOT NULL, "created_at" timestamp DEFAULT now() NOT NULL, "updated_at" timestamp DEFAULT now() NOT NULL);
    CREATE TABLE IF NOT EXISTS "notes" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "title" varchar(512) DEFAULT 'Untitled Note' NOT NULL, "workspace_id" uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, "owner_id" uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, "parent_id" uuid REFERENCES notes(id) ON DELETE SET NULL, "content" text, "published" boolean DEFAULT false NOT NULL, "published_slug" varchar(255), "created_at" timestamp DEFAULT now() NOT NULL, "updated_at" timestamp DEFAULT now() NOT NULL);
    CREATE TABLE IF NOT EXISTS "tasks" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "title" varchar(512) NOT NULL, "description" text, "workspace_id" uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, "project_id" uuid, "assignee_id" uuid REFERENCES users(id) ON DELETE SET NULL, "creator_id" uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, "status" varchar(32) DEFAULT 'todo' NOT NULL, "priority" varchar(8) DEFAULT 'p3' NOT NULL, "due_date" timestamp, "created_at" timestamp DEFAULT now() NOT NULL, "updated_at" timestamp DEFAULT now() NOT NULL);
    CREATE TABLE IF NOT EXISTS "notifications" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "user_id" uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, "type" varchar(32) NOT NULL, "title" varchar(512) NOT NULL, "body" text NOT NULL, "resource_id" uuid, "resource_type" varchar(32), "read" boolean DEFAULT false NOT NULL, "created_at" timestamp DEFAULT now() NOT NULL);
    CREATE TABLE IF NOT EXISTS "permissions" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "resource_id" uuid NOT NULL, "resource_type" varchar(32) NOT NULL, "user_id" uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, "role" varchar(32) NOT NULL, "expires_at" timestamp, "created_at" timestamp DEFAULT now() NOT NULL);
    CREATE TABLE IF NOT EXISTS "share_links" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "resource_id" uuid NOT NULL, "resource_type" varchar(32) NOT NULL, "role" varchar(32) NOT NULL, "expires_at" timestamp, "password" varchar(255), "created_at" timestamp DEFAULT now() NOT NULL);
    CREATE TABLE IF NOT EXISTS "audit_logs" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "workspace_id" uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, "user_id" uuid NOT NULL REFERENCES users(id) ON DELETE SET NULL, "action" varchar(128) NOT NULL, "resource_type" varchar(32), "resource_id" uuid, "metadata" jsonb, "ip_address" varchar(45), "user_agent" varchar(512), "created_at" timestamp DEFAULT now() NOT NULL);
    CREATE TABLE IF NOT EXISTS "email_accounts" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "user_id" uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, "email" varchar(320) NOT NULL, "display_name" varchar(255), "imap_host" varchar(255) NOT NULL, "imap_port" integer NOT NULL, "imap_secure" boolean DEFAULT true NOT NULL, "imap_password" varchar(512) NOT NULL, "smtp_host" varchar(255) NOT NULL, "smtp_port" integer NOT NULL, "smtp_secure" boolean DEFAULT true NOT NULL, "smtp_password" varchar(512) NOT NULL, "created_at" timestamp DEFAULT now() NOT NULL, "updated_at" timestamp DEFAULT now() NOT NULL);
    CREATE TABLE IF NOT EXISTS "cal_events" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "title" varchar(512) NOT NULL, "description" text, "workspace_id" uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, "owner_id" uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, "start_date" timestamp NOT NULL, "end_date" timestamp NOT NULL, "location" varchar(512), "color" varchar(16) DEFAULT '#3b82f6' NOT NULL, "is_all_day" boolean DEFAULT false NOT NULL, "created_at" timestamp DEFAULT now() NOT NULL, "updated_at" timestamp DEFAULT now() NOT NULL);
    CREATE TABLE IF NOT EXISTS "chat_channels" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "name" varchar(128) NOT NULL, "description" text, "workspace_id" uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, "member_count" integer DEFAULT 0 NOT NULL, "created_at" timestamp DEFAULT now() NOT NULL);
    CREATE TABLE IF NOT EXISTS "chat_messages" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "channel_id" uuid NOT NULL REFERENCES chat_channels(id) ON DELETE CASCADE, "user_id" varchar(255) NOT NULL, "user_name" varchar(255) NOT NULL, "body" text NOT NULL, "attachments" jsonb DEFAULT '[]'::jsonb NOT NULL, "reactions" jsonb DEFAULT '[]'::jsonb NOT NULL, "thread_id" uuid, "reply_count" integer DEFAULT 0 NOT NULL, "created_at" timestamp DEFAULT now() NOT NULL);
    CREATE TABLE IF NOT EXISTS "meetings" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "title" varchar(512) NOT NULL, "host_id" varchar(255) NOT NULL, "started_at" timestamp DEFAULT now() NOT NULL, "ended_at" timestamp, "recording" boolean DEFAULT false NOT NULL, "participants" jsonb DEFAULT '[]'::jsonb NOT NULL);
    CREATE TABLE IF NOT EXISTS "forms" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "title" varchar(512) NOT NULL, "description" text, "status" varchar(16) DEFAULT 'draft' NOT NULL, "questions" jsonb DEFAULT '[]'::jsonb NOT NULL, "response_count" integer DEFAULT 0 NOT NULL, "workspace_id" uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, "owner_id" uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, "created_at" timestamp DEFAULT now() NOT NULL);
    CREATE TABLE IF NOT EXISTS "form_responses" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "form_id" uuid NOT NULL REFERENCES forms(id) ON DELETE CASCADE, "answers" jsonb DEFAULT '{}'::jsonb NOT NULL, "submitted_at" timestamp DEFAULT now() NOT NULL);
    CREATE TABLE IF NOT EXISTS "sign_requests" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "document_id" uuid NOT NULL, "document_name" varchar(512) DEFAULT 'Untitled Document' NOT NULL, "signer_email" varchar(320) NOT NULL, "signer_name" varchar(255) NOT NULL, "sender_name" varchar(255) NOT NULL, "status" varchar(16) DEFAULT 'pending' NOT NULL, "fields" jsonb DEFAULT '[]'::jsonb NOT NULL, "sent_at" timestamp DEFAULT now() NOT NULL, "signed_at" timestamp, "decline_reason" text);
  `
  
  // Split by semicolons and execute each statement
  const statements = sql.split(';').filter(s => s.trim())
  for (const stmt of statements) {
    await client.unsafe(stmt)
  }
  console.log("✅ All tables created")
  await client.end()
}

migrate().catch(err => { console.error("Migration failed:", err); process.exit(1) })
